Move page loading progress bar around the refresh button
Igalia/wolvic pull request #1010
Opened 2023-09-24 22:15 UTC by HollowMan6

The address bar is hidden in kiosk mode, so we should have the progress bar somewhere else.

Also, it's not a good idea to have a loading view inserted before url text, which can cause distraction as the position of the URL text can keep changing.

Resolve #299

https://github.com/Igalia/wolvic/assets/43995067/61d1269d-86b9-4a9b-8118-63438e440a77

2023-09-25 11:26 UTC, svillar reviewed
Changes look good to me. @felipeerias how does it fit with your UI revamp plans?

2023-09-28 16:31 UTC, svillar requested changes
Unfortunately we cannot enable it because surprisingly it does not work in all the platforms we support. I noticed that it's broken in Pico

2023-09-28 16:36 UTC, svillar commented
https://github.com/Igalia/wolvic/assets/1826122/78704046-21c3-4446-9428-795262d5f012

See what it looks like in Pico

2023-09-28 16:39 UTC, HollowMan6 commented
That's interesting, looks like they have customized the ProgressBar there

2023-09-28 16:44 UTC, HollowMan6 commented on app/src/main/res/anim/no.xml
Maybe somehow we can add the rotation animation manually here, so that for all the platform we can have that rotated somehow.

2023-09-28 20:18 UTC, HollowMan6 commented
> Unfortunately we cannot enable it because surprisingly it does not work in all the platforms we support. I noticed that it's broken in Pico

Added the animation to rotate the progress bar, can you help me test in Pico and see what does it looks like?

2023-09-29 10:26 UTC, svillar commented
> > Unfortunately we cannot enable it because surprisingly it does not work in all the platforms we support. I noticed that it's broken in Pico
> 
> Added the animation to rotate the progress bar, can you help me test in Pico and see what does it look like? @svillar

This is how it looks now

https://github.com/Igalia/wolvic/assets/1826122/a9e3d95c-8098-4868-a390-bc2aaba26d0d

two comments:
1. looks different than in other platforms
2. seems to last longer than needed

I guess 1. is because Pico's android version. Not sure if we can do something about 2.

In the other devices it still looks great

2023-09-29 12:38 UTC, HollowMan6 commented
> two comments:
> 
> 1. looks different than in other platforms
> 2. seems to last longer than needed
> 
> I guess 1. is because Pico's android version. Not sure if we can do something about 2.
> 
> In the other devices it still looks great

Yeah, maybe it's because of Pico's Android version, which leads to Pico's ProgressBar looking different than others.

For 2, of course, we can modify the duration here to make it faster, but this will also make the progressBar look even faster (since it's already rotating there). Since I don't have a Pico device, I don't know what will be the best parameter here to fine-tune the UI effect so that we can have the optimal on all the devices. https://github.com/Igalia/wolvic/pull/1010/files#diff-74e9484af8eff0bd67f1eab07581f9f10496f9e26bf5e7a467b8885155823657R9

2023-10-04 14:17 UTC, svillar approved these changes
Let's land this then as @felipeerias is OK with it (confirmed offline)

2023-10-04 14:17 UTC, merged