Updated App Lab warning message
Igalia/wolvic pull request #1049
Opened 2023-10-06 15:15 UTC by felipeerias

Update the warning message that appears on startup on the AppLab version of Wolvic.

This is the updated message:

> **Support ending soon**
> 
> This "App Lab" version of Wolvic will be removed by the end of October 2023.
> 
> Please install the latest version of Wolvic from the Meta Quest Store.
> 
> IMPORTANT: unless you use Sync, the new Wolvic app will not have your bookmarks and tabs.

2023-10-06 15:20 UTC, felipeerias commented
![image](https://github.com/Igalia/wolvic/assets/1412060/8e248a81-8791-4539-af5d-95a6d081209a)

![image](https://github.com/Igalia/wolvic/assets/1412060/9f83cbb9-f500-4a63-a433-d32bef33aed6)

2023-10-06 15:21 UTC, felipeerias commented
The App Lab version with these changes is at the [felipeerias/v1.4.1-applab](https://github.com/Igalia/wolvic/tree/felipeerias/v1.4.1-applab) branch.

2023-10-06 17:17 UTC, HollowMan6 requested changes
As you may already know, the CI fails because you accidentally removed a lot of strings. I'm not sure why it ends up like this but obviously, we still need them.

Below is just a portion of them.

2023-10-06 17:17 UTC, HollowMan6 commented on app/src/main/res/values/strings.xml
> -
Should not remove this

2023-10-06 17:17 UTC, HollowMan6 commented on app/src/main/res/values/strings.xml
> -
Should not remove this

2023-10-06 17:17 UTC, HollowMan6 commented on app/src/main/res/values/strings.xml
> -
Should not remove this

2023-10-06 17:17 UTC, HollowMan6 commented on app/src/main/res/values/strings.xml
> -
Should not remove this

2023-10-06 17:17 UTC, HollowMan6 commented on app/src/main/res/values/strings.xml
> -
Should not remove this

2023-10-06 17:17 UTC, HollowMan6 commented on app/src/main/res/values/strings.xml
> -
Should not remove this

2023-10-07 02:36 UTC, felipeerias commented
Sorry about the problems. I developed this patch against an earlier version of Wolvic and it seems that there was an issue when bringing it to the main branch.

2023-10-07 08:48 UTC, HollowMan6 approved these changes
Now LGTM

2023-10-09 07:46 UTC, svillar approved these changes

2023-10-09 07:46 UTC, merged