Enable switch passthrough in video brightness settings
Igalia/wolvic pull request #1119
Opened 2023-11-24 12:49 UTC by HollowMan6

We should switch back to environments when users adjust the brightness in passthrough mode, as those brightness settings don't work for passthrough environment.

Also we should allow users to easily switch to passthrough mode when watching videos.

![com igalia wolvic-20231124-134049](https://github.com/Igalia/wolvic/assets/43995067/b3c2fa2a-c4c0-43b3-87a1-09480ff7ab85)

2023-11-24 15:37 UTC, svillar requested changes

2023-11-24 15:37 UTC, svillar commented on app/src/common/shared/com/igalia/wolvic/ui/widgets/menus/BrightnessMenuWidget.java
> +        }
setSelectedItem(isPassthroughEnabled ? 3 : 1)

2023-11-24 15:37 UTC, svillar commented on app/src/common/shared/com/igalia/wolvic/ui/widgets/menus/BrightnessMenuWidget.java
> +        }
I think we better hide the brightness icon when passthrough is enabled.

2023-11-24 17:35 UTC, HollowMan6 commented
> I think we better hide the brightness icon when passthrough is enabled.

Yeah, that sounds good, maybe I should rework this PR

2023-11-24 18:19 UTC, HollowMan6 commented
Updated so that we just simply hide the brightness button when playing video in Passthrough

2023-11-27 09:42 UTC, svillar approved these changes
Thanks! good catch

2023-11-27 09:42 UTC, merged