Properly support vertical videos
Igalia/wolvic pull request #1195
Opened 2024-01-22 12:27 UTC by svillar

Popular streaming services host more and more videos in vertical format usually recorded with mobile phones. Wolvic was not properly handling the case of watching them in fullscreen mode. There were 2 reasons for that:
1. The code resizing the window for fullscreen assumed horizontal formats
2. The code handling fullscreen events was not properly retrieving the media information (like size) from the web engine

2024-01-22 12:39 UTC, svillar commented
![Before and After](https://github.com/Igalia/wolvic/assets/1826122/b9ef9d63-868f-4dee-8314-ffb9e28f7caa)

2024-01-22 19:41 UTC, HollowMan6 reviewed
It will be good if we can resize the screen size dynamically according to the size of the video we are currently playing, since we can get into full screen with horizontal ads: 

https://github.com/Igalia/wolvic/assets/43995067/101c3c70-a1a2-44d6-b1e3-2d35e01e06e2

2024-01-22 21:04 UTC, HollowMan6 approved these changes
This now LGTM as https://github.com/Igalia/wolvic/pull/1195#pullrequestreview-1837230075 is kind of unaddressable.

2024-01-22 22:13 UTC, HollowMan6 reviewed
Just noticed 2 things:

- Looks like we will still get back to horizontal playing if we resize in full screen and click on the preset scales.
- Also the minimum width in resize should be smaller here to fit the new need. now if we resize, we won't get back to the original one.
- We might want to fix the ratio when resizing for horizontal videos, or it will cause some edges to be cut off

2024-01-23 09:01 UTC, svillar commented
> It will be good if we can resize the screen size dynamically according to the size of the video we are currently playing, since we can get into full screen with horizontal ads.

Hmm that's precisely what this patch does, we listen for the media onfullscreen which is the event that carries the video size information.

2024-01-23 09:02 UTC, svillar commented
> Just noticed 3 things for resizing:
> 
> * Looks like we will still get back to horizontal playing if we resize in full screen and click on the preset scales.
> * Also the minimum width in resize should be smaller here to fit the new need. now if we resize, we won't get back to the original one.
> * We might want to fix the ratio when resizing for horizontal videos, or it will cause some edges to be cut off

Really good points, I'll check them.

2024-01-23 09:05 UTC, HollowMan6 commented
> > It will be good if we can resize the screen size dynamically according to the size of the video we are currently playing, since we can get into full screen with horizontal ads.
> 
> Hmm that's precisely what this patch does, we listen for the media onfullscreen which is the event that carries the video size information.

I mean, the size of the video can still change even though you keep playing it in full-screen, so only checking the video size `onFullScreen` is not enough, check the video and comments below there: https://github.com/Igalia/wolvic/pull/1195#pullrequestreview-1837230075

2024-01-23 09:11 UTC, svillar commented
> > > It will be good if we can resize the screen size dynamically according to the size of the video we are currently playing, since we can get into full screen with horizontal ads.
> > 
> > 
> > Hmm that's precisely what this patch does, we listen for the media onfullscreen which is the event that carries the video size information.
> 
> I mean, the size of the video can still change even though you keep playing it in full-screen, so only checking the video size `onFullScreen` is not enough, check the video and comments below there: [#1195 (review)](https://github.com/Igalia/wolvic/pull/1195#pullrequestreview-1837230075)

Ah I see what you mean now. Off the top of my head I don't remember any geckoview API that covers that situation but I'll double check anyway.

2024-01-23 09:12 UTC, svillar commented
Converted to draft in order not to land it accidentally

2024-01-24 18:48 UTC, HollowMan6 requested changes
There are still some bugs for resizing in vertical mode:
- Default size is much bigger than 1x (still a little bit smaller than 2x)
- 2x now is almost the same size as 0.5x (the problem should lie in 0.5x)
- When you drag the border, you can't get as small as 1x.

https://github.com/Igalia/wolvic/assets/43995067/adb4a037-4183-46d5-b14a-4937c8f3fc95

https://github.com/Igalia/wolvic/assets/43995067/512755cd-69d0-423c-a955-027a08ae4a23

2024-01-25 11:14 UTC, svillar commented
Haven't checked them in detail but note that there are constrains we apply for horizontal and vertical sizes. In particular the max vertical size is smaller than the horizontal one.

The thing about 0.5x seems a bug indeed

2024-01-25 19:06 UTC, HollowMan6 requested changes
Did some research, and I found that, actually even for horizontal ones, the default video size is always somehow around 1.5x when you first enter full-screen mode. Since this is an old behavior, this can be ignored:

> Default size is much bigger than 1x (still a little bit smaller than 2x)

The rest can be fixed according to my suggestion in the change request below.

I think we will be ready to merge this PR after a rebase and integrating the following suggestion. Nice work @svillar 💪

2024-01-26 09:28 UTC, svillar commented on app/src/common/shared/com/igalia/wolvic/ui/widgets/WindowWidget.java
> +            float worldOrthogonalSize = worldSize / aAspect;
Makes sense

2024-01-26 10:34 UTC, HollowMan6 approved these changes
Now LGTM

2024-01-26 11:24 UTC, merged