Implement Zoom UI in Hamburger Menu
Igalia/wolvic pull request #1248
Opened 2024-02-13 10:20 UTC by mshin-wolvic

Unlike the general menu items with ImageView&TextView layout, a Zoom menu has ImageView&TextView&+/- ImageViews layout and only +/- ImageViews should handle hover and click events.
This patch configures the zoom layout and add the relevant code. The +/- ImageViews are connected to the page zoom feature, and this Zoom UI appears only in chromium-backend.

2024-02-14 10:21 UTC, zakharvoit requested changes
Left one nit, but I'd like somebody else from the team to review since I'm not very familiar with wolvic/ code.

2024-02-14 10:21 UTC, zakharvoit commented on app/build.gradle
> +        buildConfigField "Boolean", "ENABLE_PAGE_ZOON", "false"
ZOOM

2024-02-15 10:22 UTC, svillar reviewed
We are not adding translations in PRs anymore because that messes up Weblate, so let's just include the new strings in strings.xml and remove the translations.

2024-02-15 10:39 UTC, svillar commented
Ah and another comment, please add a '%' after the zoom level in the UI, otherwise seeing 100, 175 etc looks weird

2024-02-16 01:42 UTC, mshin-wolvic commented
> We are not adding translations in PRs anymore because that messes up Weblate, so let's just include the new strings in strings.xml and remove the translations.

Done.

> Ah and another comment, please add a `%` after the zoom level in the UI, otherwise seeing 100, 175 etc looks weird

Done.

Thanks. :)

2024-02-16 11:56 UTC, svillar approved these changes
Wonderful!

2024-02-16 11:56 UTC, merged