[chromium] Implement Text Selection
Igalia/wolvic pull request #1306
Opened 2024-03-13 08:06 UTC by mshin-wolvic

This patch implements to show the text selection's action UI and paste UI and execute selection actions by the user.

2024-03-15 08:52 UTC, zakharvoit requested changes

2024-03-15 08:52 UTC, zakharvoit commented on app/src/chromium/assets/snapshot_blob_64.bin
I believe the binary files are added by accident?

2024-03-15 09:38 UTC, mshin-wolvic commented on app/src/chromium/assets/snapshot_blob_64.bin
Oh, Thanks for catching it.

2024-03-21 09:46 UTC, svillar approved these changes
beautiful

2024-03-21 09:47 UTC, merged