Do not launch the crash handler dialog
Igalia/wolvic pull request #1397
Opened 2024-05-02 17:16 UTC by javifernandez

We don't have a service to collect and analyze the coredumps generated after crashes, so it's better to avoid launching the dialog to ask the user about sending it.

2024-05-02 17:43 UTC, svillar requested changes
This also prevents Wolvic from sending core dumps if crash reporting is enabled. What do you think about removing also the setting in the UI as it will do nothing?

As far as I know the only way to change this setting through the UI is precisely through the CrashDialogWidget, which is not launched anymore.

2024-05-02 17:47 UTC, svillar commented on app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java
> -        checkForCrash();
I was also thinking what about keeping the call here and add an unconditional return at the beginning of the method with a comment explaining that will be enabled later once we have the required infra?

2024-05-03 09:22 UTC, javifernandez commented
> This also prevents Wolvic from sending core dumps if crash reporting is enabled. What do you think about removing also the setting in the UI as it will do nothing?

As far as I know the only way to change this setting through the UI is precisely through the CrashDialogWidget, which is not launched anymore.

2024-05-03 12:08 UTC, svillar approved these changes
Thanks, let's do it

2024-05-03 12:08 UTC, merged