Use Khronos' OpenXR loader from Maven when supported
Igalia/wolvic pull request #1405
Opened 2024-05-06 15:45 UTC by svillar

Most of the platforms used to distribute their own implementations/builds of the OpenXR loader. It was traditionally part of the propietary SDKs distributed by vendors. As they were under an EULA we had to keep them in a private repository only available to core devs (obviously any other external dev could download them on their own).

More recently, and driven by the AOSP flavor effort, we started to build the Khronos OpenXR loader from sources. Fortunatelly we got a well documented report explaining how to use the loader directly from the central Maven repository. This greatly simplifies the build process and also improves the open-source feel of the project by reducing our deps with the third-party repo.

So far this option is now available for the following flavors:
* Meta Quest2, Quest3, QuestPro (requires firmware v62+)
* Lynx R1
* Magic Leap 2

It does not work for neither HVR, nor SnapdragonSpaces based devices nor Pico. For these ones we still need to rely on the loader from the SDK.

Fixes #1394

2024-05-06 15:48 UTC, svillar commented
Note that this requires firmware v62+ in Meta devices. It's easy to check that in OpenXR but it's likely too late. I'd love to have some "external" mechanism to prevent/filter out Wolvic from executing depending on the firmware version. v62 is from February so perhaps a bit risky to enable it in a release in the following moths.

2024-05-08 21:34 UTC, javifernandez approved these changes
I'd be more explicit in the commit message that this change breaks Wolvic in Meta platforms <v62.

2024-08-31 00:49 UTC, javifernandez requested changes
The commit message of the second commit is incomplete: 

"Should the test fail, a dialog with a text asking user to upgrade the" ....

2024-09-04 08:43 UTC, svillar commented
> The commit message of the second commit is incomplete:
> 
> "Should the test fail, a dialog with a text asking user to upgrade the" ....

Good catch, updated.

2024-09-04 10:29 UTC, javifernandez requested changes
In quest there is a system window that appears before showing Wolvic's logo. I doesn't show for too long, but it's clearly noticeable. 

In other systems (eg, Pico) this window it's not shown, though.

2024-09-05 10:54 UTC, svillar commented
> In quest there is a system window that appears before showing Wolvic's logo. I doesn't show for too long, but it's clearly noticeable.
> 
> In other systems (eg, Pico) this window it's not shown, though.

Do you think that's a blocker?

2024-09-09 12:27 UTC, javifernandez commented
> > In quest there is a system window that appears before showing Wolvic's logo. I doesn't show for too long, but it's clearly noticeable.
> > In other systems (eg, Pico) this window it's not shown, though.
> 
> Do you think that's a blocker?

I wouldn't say it's a blocker to merge it in main, but I wouldn't select for any stable release without a solution for this issue.

2024-09-09 12:29 UTC, javifernandez approved these changes
I approve the change as it is now, but we should file a bug about the initial (void) window launched by the Control Version activity; I'd rather make it not visible, or something like that.

2024-09-13 14:07 UTC, merged

2024-09-16 21:20 UTC, rpavlik commented on app/CMakeLists.txt
> +        include_directories(${CMAKE_SOURCE_DIR}/../third_party/OpenXR-SDK/include)
FYI, you should be able to do this instead:

```
target_link_libraries(native-lib PRIVATE OpenXR::headers)
```

to just use the headers from the AAR