Add Chromium backend build instructions
Igalia/wolvic pull request #1442
Opened 2024-06-04 12:21 UTC by svillar

As the README.md file is already way too crowded we've decided to add them in a separate file at least until we don't reorganize the documentation.

Fixes #1437

2024-06-07 09:57 UTC, felipeerias commented
I tried the instructions to compile Chromium from scratch and they were very incomplete. Perhaps we are better off telling people to follow the official guide to compile Chromium and then add our fork.

2024-06-07 10:55 UTC, svillar commented
> I tried the instructions to compile Chromium from scratch and they were very incomplete. Perhaps we are better off telling people to follow the official guide to compile Chromium and then add our fork.

Agree I totally forgot to add a link to the chromium official build instructions

2024-06-11 05:32 UTC, felipeerias commented
The following sequence worked for me with a fresh install of Chromium.

Reference: https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md

* Install depot tools and add them to the path
* `mkdir chromium && cd chromium`
* `fetch --nohooks --no-history chromium`
* edit `./.gclient`

```
solutions = [
  {
    "name": "src",
    "url": "https://chromium.googlesource.com/chromium/src.git",
    "managed": False,
    "custom_deps": {},
    "custom_vars": {
      "checkout_pgo_profiles": True, 
    },
  },
]
target_os = ["android"]
```

* `cd src`
* `./build/install-build-deps.sh`
* `gclient runhooks`
* `gn gen out/Default`
* edit `./out/Default/args.gn` (debug or release version)

```
target_os = "android"
target_cpu = "arm64"
is_official_build = true
ffmpeg_branding="Chrome"
proprietary_codecs=true
```

* `git remote add wolvic-chromium https://github.com/Igalia/wolvic-chromium`
* `git fetch wolvic-chromium`
* `git fetch --depth=1 wolvic-chromium`  to skip getting the history
  - alternatively, use something like `git fetch --depth=1288 wolvic-chromium` to get the commits that are new in our branch
* `git switch wolvic`
* `autoninja -C out/Default content_aar ui_aar`
  - here I had to add the PGO setting above and run `gclient sync`, and then compile again
* if that last command fails
  - run `autoninja -C out/Default content/shell:content_shell_resources_grit`
  - then run `autoninja -C out/Default content_aar ui_aar` again

After the compilation has finished successfully, continue with the steps to integrate the libraries into Wolvic.

2024-06-11 06:27 UTC, felipeerias requested changes

2024-06-11 06:27 UTC, felipeerias commented on CHROMIUM.md
> +After adding `chromium_aar` in user.properties and syncing gradle, you can see various build variants with Chromium suffix. Please choose one among them.
It should be `local.properties`.

2024-06-11 12:01 UTC, felipeerias commented
@svillar I have added a commit with more details about the process of downloading and building Chromium from scratch.

2024-06-11 12:02 UTC, felipeerias approved these changes
LGTM, waiting for @svillar's feedback regarding the new additions.

2024-06-11 14:24 UTC, merged