[Vision Glass] App name and China app id
Igalia/wolvic pull request #1452
Opened 2024-06-14 09:38 UTC by felipeerias

Set the app name of the Vision Glass variant to `"Wolvic Vision"` so it is shorter and easier to remember (and also doesn't get trimmed in the UI). The store description will mention that this app is intended for "Vision Glass" so people can find it.

Set the application id for China to `"com.igalia.wolvic.visionglass"`, which is the one that we are using on the China AppGallery.

2024-06-14 09:38 UTC, felipeerias commented
Draft for now, while the other Vision Glass PR are reviewed.

2024-06-19 20:43 UTC, svillar requested changes
What about directly setting the whole appId instead of having the id + suffix?

2024-06-19 20:43 UTC, svillar commented
Also I don't understand what you need to specify the id when that's the default one

2024-06-26 12:00 UTC, svillar approved these changes

2024-06-26 12:00 UTC, merged