[Pico] Add an OS version check
Igalia/wolvic pull request #1541
Opened 2024-09-13 16:00 UTC by svillar

Pico OpenXR runtime had several issues over the time. We had to add workarounds here and there to support those OS versions. As time passes by those workarounds just make the code more complex to maintain  without any real benefit (as it affects really old versions of the OS).

After this change Pico OS versions < v5.7.1 **are no longer supported**  and Wolvic will refuse to start.

This allows us to remove a lot of code workarounding runtime bugs including the legacy hand mesh renderer using spheres.

2024-09-15 16:13 UTC, javifernandez requested changes

2024-09-16 09:01 UTC, svillar commented on app/src/main/cpp/HandMeshRenderer.cpp
> -// HandMeshRendererSpheres
Yes it is because the speheres rendering was only used by pico in old OS versions

2024-09-16 11:18 UTC, javifernandez commented on app/src/main/cpp/HandMeshRenderer.cpp
> -// HandMeshRendererSpheres
ah, got it,  Thanks.

2024-09-16 11:20 UTC, javifernandez commented on app/src/common/shared/com/igalia/wolvic/VRBrowserActivity.java
> -               (DeviceType.isPicoXR() && Build.ID.compareTo(kPicoVersionPassthroughUpdate) >= 0);
> Why you are removing the OS version check to determine passthrough support ?

Ah, it's already replied in a previous comment; versions prior to v5.7.1 are no longer supported.

2024-09-16 16:10 UTC, javifernandez approved these changes
The code looks good it works well in the Pico4 with the last SO version.

2024-09-17 07:56 UTC, merged