Compare semantic versions
Igalia/wolvic pull request #1542
Opened 2024-09-16 15:21 UTC by felipeerias

Add a method `StringUtils.compareVersions()` that compares semantic versions. We assume that versions are defined as integer numbers separated by periods (`.`), but the method also takes into account empty strings and the possibility that some components can not be parsed as integers.

Use `StringUtils.compareVersions()` to check the version of the PICO operating system when enabling passthrough.

Tests are included.

2024-09-16 15:40 UTC, javifernandez approved these changes
Just commented about a possible coding-style improvement, but the code looks correct.

2024-09-16 15:40 UTC, javifernandez commented on app/src/common/shared/com/igalia/wolvic/utils/StringUtils.java
> +            String component1 = i < components1.length ? components1[i] : "0";
Nit: we can define this as a lambda, like `ToInt(component, i))` and then use it directly in the 'compare' call; something likes this: 

try {
   int comparison = Integer.compare(ToInt(component,  i), ToInt(component2, i));
}

2024-09-16 16:09 UTC, javifernandez requested changes
Hold on, perhaps we should replace the CompareBuildStrings with your new function. There are a few codepaths that depend on the OS version that are being applied incorrectly now.

2024-09-16 16:31 UTC, javifernandez commented
> Hold on, perhaps we should replace the CompareBuildStrings with your new function. There are a few codepaths that depend on the OS version that are being applied incorrectly now.

Nevermind, it's not that simple; we would need something else for the native code.

2024-09-16 16:31 UTC, javifernandez approved these changes
Looks good as a quick fix for the passwthough issue.

2024-09-18 09:36 UTC, svillar commented
After #1541 this is no longer needed

2024-09-18 09:36 UTC, closed without merging