Add Firefox Accounts to Desktop mode overrides
Igalia/wolvic pull request #209
Opened 2022-07-19 22:24 UTC by elima

This is a temporary workaround to fix login into Firefox Accounts, which has been broken unexpectedly by a change in the server behavior: it is apparently filtering by UA and the usual request we make to the OAuth page keeps loading forever, stalling the login process.

This patch forces domains where host is `accounts.firefox.com` to always use Desktop mode.

See Issue #205.

2022-07-25 10:22 UTC, svillar requested changes
The idea of changing the UA is correct but we don't need to enable desktop mode for that (that changes other stuff like viewport size...). We can use the good old UA overrides for that. You should change `userAgentOverride.json` file instead

2022-07-26 11:01 UTC, felipeerias approved these changes
LGTM

2022-07-26 11:18 UTC, felipeerias commented
This change works as expected.

While testing it, I discovered another problem related to Firefox Accounts authentication: issue https://github.com/Igalia/wolvic/issues/214

2022-07-26 12:24 UTC, svillar approved these changes

2022-07-26 12:24 UTC, merged