Enable analytics for Huawei devices
Igalia/wolvic pull request #295
Opened 2022-10-07 05:51 UTC by felipeerias

Enable `HiAnalytics` in `PlatformActivity`.

Rename `HVR_ML_API_KEY` to `HVR_API_KEY`.

2022-10-07 09:00 UTC, svillar requested changes
I am not sure the rename pays off as it'll force developers to update their userProperties files. Is there any strong reason to do that?

If the answer is yes, then I'd ask you to split this change in two different commits, one for the rename and some other for the actual fix.

2022-10-09 16:08 UTC, felipeerias commented on app/src/hvr/java/com/igalia/wolvic/PlatformActivity.java
> +        HiAnalyticsTools.enableLog();
I have changed it so it is only enabled in debug builds.

2022-10-09 16:11 UTC, felipeerias commented
@svillar It is a small thing, but I think that renaming `HVR_ML_API_KEY` to `HVR_API_KEY` would make sense. I will open a separate PR and we talk about it there.

2022-10-10 09:03 UTC, svillar approved these changes
Nice!. Thanks

2022-10-10 09:03 UTC, merged

2022-10-10 09:04 UTC, svillar commented
> @svillar It is a small thing, but I think that renaming `HVR_ML_API_KEY` to `HVR_API_KEY` would make sense. I will open a separate PR and we talk about it there.

Sure, I'm fine with renamings but I prefer specific PRs for them, that helps with bisects, blames etc...