[OpenXR] Vertically flip OpenXR layers in Meta
Igalia/wolvic pull request #386
Opened 2022-12-20 21:35 UTC by svillar

Most OpenXR layers in Meta appear upside down, i.e., flipped in the y direction. In particular we're talking about Quad,
Cylinder and Equirect layers (cubemaps are not affected).

This does not happen in other devices using XRLayers (like Pico) so it must be definitely a Meta implementation issue.
In order to fix that we use the XR_FB_composition_layer_image_layout extension developed precisely by Meta.

We were using this only for equirect layers but it turns out that quad and cylinder are also affected, so we've generalized
the same fix for the other layer types.

2022-12-21 10:07 UTC, elima commented
Looks good, just left a nitpick comment and a suggestion.

2022-12-21 12:29 UTC, elima requested changes

2022-12-21 12:31 UTC, svillar commented on app/src/openxr/cpp/OpenXRLayers.h
> +    XrCompositionLayerImageLayoutFB mLayerImageLayout { .type = XR_TYPE_COMPOSITION_LAYER_IMAGE_LAYOUT_FB, .next = XR_NULL_HANDLE, .flags = XR_COMPOSITION_LAYER_IMAGE_LAYOUT_VERTICAL_FLIP_BIT_FB };
oki

2022-12-22 11:20 UTC, elima approved these changes
Looks good, thanks!

2022-12-22 11:21 UTC, merged