Add a new flavor dimension "backend"
Igalia/wolvic pull request #491
Opened 2023-02-14 03:49 UTC by duswnchl

Currently the backend for a browser engine can be selected by  userProperties.backend. This PR adds a new flavor dimension "backend" and we can choose the backend from the build variant.

So far, "chromium"/"webkit" is available only when userProperties.chromium_aar/userProperties.webkit_aar are set.

2023-02-14 08:51 UTC, svillar requested changes
Looking great. I'll have to test it but in the meantime I have just a few nits (typos mostly)

2023-02-14 08:51 UTC, svillar commented on app/build.gradle
> +def isChromiumAvaiable = {
Typo: Avaiable->Available

2023-02-14 08:51 UTC, svillar commented on app/build.gradle
> +        // Create variants for chromium/webkit, only when they are avialble
Typo: avialble->available

2023-02-14 08:51 UTC, svillar commented on app/build.gradle
> +def isWebKitAvaiable = {
Typo: same as before

2023-02-14 09:06 UTC, duswnchl commented on app/build.gradle
> +def isChromiumAvaiable = {
Oops! Thanks for the catch :) Done.

2023-02-14 09:06 UTC, duswnchl commented on app/build.gradle
> +        // Create variants for chromium/webkit, only when they are avialble
Done.

2023-02-14 09:06 UTC, duswnchl commented on app/build.gradle
> +def isWebKitAvaiable = {
Done.

2023-02-14 10:53 UTC, zakharvoit commented on app/build.gradle
> +        webkitImplementation fileTree(dir: gradle."userProperties.webkit_aar", include: ['*.aar'])
I think it should be "implementation"

2023-03-01 10:49 UTC, jdapena requested changes
It mostly looks good to me (apart from a minor nitpick). I'd likely prefer some refactor in build.gradle to avoid repeating same code in each backend, but that definitely needs some thinking before doing.

2023-03-01 10:49 UTC, jdapena commented on .github/workflows/ci.yml
> +        flavour: [assembleOculusvrArm64WorldGecko, assembleHvrArm64WorldGecko, assemblePicoxrArm64WorldGecko]
Nit: maybe time to make this array multiline, so it is a bit more version control friendly.

2023-03-02 09:33 UTC, svillar reviewed
I've a couple of doubts, once resolved it should be ready to merge.

2023-03-02 09:33 UTC, svillar commented on app/build.gradle
> +        }
Why is this preferable over having `'src/common/' + getBackend()` above?

2023-03-02 09:33 UTC, svillar commented on app/build.gradle
> +        }
Not really sure, what this is about? Could you explain why it's needed?

2023-03-02 16:35 UTC, jdapena approved these changes

2023-03-06 10:22 UTC, svillar commented on app/build.gradle
> +        }
fair enough, thanks for the explanations

2023-03-07 21:27 UTC, svillar approved these changes
Awesome work

2023-03-07 21:27 UTC, merged