Fix #573: Ensure that store builds use OpenXR
Igalia/wolvic pull request #615
Opened 2023-04-15 10:29 UTC by kavi-kumaran

This pull request fixes #573. It prevents from submitting a non OpenXR build to an store. It throw an error if a store flavor is built with openxr=false.

2023-04-15 10:30 UTC, kavi-kumaran commented
Tagging @svillar for review

2023-04-18 12:01 UTC, svillar requested changes
Needs some changes. Also please do not include the first 3 commits (you can remove them locally and then force-push)

2023-04-18 12:01 UTC, svillar commented on app/build.gradle
> +        if (store == 'generic' && !project.hasProperty('openxr') || project.getProperty('openxr') == false) {
Hmm but `generic`is precisely used for non store builds. The point is that store builds must always use `openxr=true`

2023-04-19 09:37 UTC, closed without merging

2023-04-19 09:38 UTC, svillar commented
Hmm so what happened here? are you planning to work on this?

2023-04-19 09:40 UTC, kavi-kumaran commented
> Hmm so what happened here? are you planning to work on this?

Yes