[Chromium] Support WebXR
Igalia/wolvic pull request #642
Opened 2023-05-02 10:52 UTC by mshin-wolvic

- Set the external context to access the shared memory in the Chromium
- Set the wrapper SurfaceTexture class as Chromium's one

Depends on https://github.com/Igalia/wolvic-chromium/pull/10

2023-05-02 11:03 UTC, svillar reviewed
The commit message needs a description explaining the change. Ideally prepend [Chromium] to the title.part.

As a general comment, I understand this as a straightforward way to get WebXR support ASAP. From that POV I think it's fine and I won't ask you to waste your precious time doing some refactoring. 

However we cannot leave this class in the common code as is. `GeckoSurfaceTexture` should not be placed in common code. I know this class is not exactly specific to Gecko, actually is mostly about JNI calls, so it should be easily renamable/refactorizable. 

So summarizing, I won't ask for additional changes now. I'll leave this open so that others could work on the refactoring.

2023-05-02 12:25 UTC, svillar commented
So, @mshin-wolvic what do you think about rebasing it on top of https://github.com/Igalia/wolvic/pull/644 once it's approved? Would that work?

You'd just need to add an `#elif` for chromium if I understand it correctly.

2023-05-02 14:24 UTC, svillar requested changes
Explicitly asking for changes although I've already done that in the comments. https://github.com/Igalia/wolvic/pull/644 is already merged

2023-05-03 03:09 UTC, mshin-wolvic commented
Rebased.

2023-05-03 10:39 UTC, svillar approved these changes

2023-05-03 10:40 UTC, merged