Enable passthrough for the Snapdragon spaces runtime
Igalia/wolvic pull request #649
Opened 2023-05-05 16:54 UTC by javifernandez

This PR adds the Snapdragon devices to the list of the ones with Passthrough support. This will make the appropriated menu item to be visible in the hamburger menu. 

The Snapdragon devices were using the OpenXRPassthroughStrategyBlendMode strategy, which uses the  XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND flag in the XrFrameEndInfo data structure. Unfortunately, the runtime doesn't support this flag. 

A new  OpenXRPassthroughStrategyNoSkybox class for the strategy pattern is defined for this case, which assigns a XR_ENVIRONMENT_BLEND_MODE_OPAQUE flag (the default) instead.  

In order to activate the passthrough is enough to avoid rendering the cube layer with the skybox, so that the runtime draws a transparent background.

2023-05-06 07:08 UTC, svillar requested changes
Hmm the thing is that I don't see how this prevents the skybox form being drawn. We're still drawing it, OPAQUE is the default blend mode we've been using

2023-05-08 08:40 UTC, javifernandez commented
> Hmm the thing is that I don't see how this prevents the skybox form being drawn. We're still drawing it, OPAQUE is the default blend mode we've been using

When the passthouugh is enabled from the UI we process the codepath defined DeviceDelegateOpenXR.cpp:1130, so we don't update the m.cubeLayer where the skybox is being draw. 

Regarding the OPAQUE mode, we may thing about better ways to implement the strategy pattern, but we need to return something for this "no-skybox" strategy to implement environmentBlendModeForPassthrough, and OPAQUE seemed the more appropriated and easier to implement option.

2023-05-08 14:49 UTC, svillar commented
> > Hmm the thing is that I don't see how this prevents the skybox form being drawn. We're still drawing it, OPAQUE is the default blend mode we've been using
> 
> When the passthouugh is enabled from the UI we process the codepath defined DeviceDelegateOpenXR.cpp:1130, so we don't update the m.cubeLayer where the skybox is being draw.
>

Ah right, I forgot that we never paint the skybox in case passthrough is enabled, in this case we just simply don't do anything which makes sense.

> Regarding the OPAQUE mode, we may thing about better ways to implement the strategy pattern, but we need to return something for this "no-skybox" strategy to implement environmentBlendModeForPassthrough, and OPAQUE seemed the more appropriated and easier to implement option.

Nah, the OPAQUE mode is perfectly fine, now that the previous doubt was clarified everything is fine now. I'll just test it and approve if everything works fine, as the patch is good.

2023-05-09 14:18 UTC, svillar approved these changes
Looks nice!

2023-05-09 14:18 UTC, merged