Automate application name change for hvr flavor in mainland China
Igalia/wolvic pull request #682
Opened 2023-05-19 05:00 UTC by kavi-kumaran

This pr fixes #653.This PR automates the application name change for the hvr flavor in mainland China. It adds a new resource value and modifies the build script to set the application name to "Wolvic" for the hvr flavor in mainland China, eliminating the need for manual replacements before generating packages.

2023-05-19 05:03 UTC, kavi-kumaran commented
Tagging @svillar for review. please not for checking it in debug mode change the app_name in the app/src/debug/res/non_L10n.xml from Wolvic VR Browser(Dev) to @string/app_name_value

2023-05-19 07:08 UTC, svillar requested changes
Hmm can't we just simply add a new resource file with that value in a specific directory? Something like `app//src/hvrCnArm...`. Normally this kind of things are properly merged

2023-05-25 16:53 UTC, kavi-kumaran commented
I attempted to include a new resource file specifically for the hvrCnArm build. I placed the new resource file within the sourceSets of the hvr variant, using an if condition to ensure it is added only when the country is 'cn'. However, it seems to disregard the values from the newly added resource file and instead pulls from the main or debug resource file. Any idea what I could have missed ?

2023-06-21 10:23 UTC, svillar commented
We can close this now as we're switching to "Wolvic" for all platforms, see #741

2023-06-21 10:23 UTC, closed without merging