[Chromium] Add explicit dependency on androidx.core
Igalia/wolvic pull request #830
Opened 2023-07-11 13:08 UTC by zakharvoit

This change adds an explicit dependency on androidx.core and updates the compile sdk version to 33 (required by androidx.core:1.10.1).

This is required by the new versions of the Chromium backend.

2023-07-15 22:11 UTC, svillar requested changes

2023-07-15 22:11 UTC, svillar commented on app/build.gradle
> +    implementation deps.support.core
Shouldn't we add this with the other `chromiumImplementation` as it looks like we don't need it for gecko?

2023-07-17 03:20 UTC, zakharvoit commented
It seems like https://github.com/Igalia/wolvic/pull/820 is almost ready to be merged, so I'm going to wait for it. I think this PR will not be needed anymore after the full dependencies update.

2023-07-24 11:42 UTC, svillar commented
Closing as #820 was already merged with the compile sdk upgrade

2023-07-24 11:42 UTC, closed without merging