Chromium: Add targetRayOrientation field to VRControllerState
Igalia/wolvic pull request #849
Opened 2023-07-19 08:20 UTC by zakharvoit

Update moz_external_vr.h to include an additional field that represents the orientation component of the controller's target ray. This field is required by the Chromium's vr_service.mojom API.

2023-07-19 12:50 UTC, tiagovignatti approved these changes
LGTM. 

Though, it would be nice to hear from other reviewers how `targetRayPose` is being used for Wolvic Gecko on non-Meta Quest devices.

2023-07-19 14:48 UTC, jdapena approved these changes

2023-07-19 16:45 UTC, svillar requested changes

2023-07-24 10:50 UTC, svillar commented
Let's close this as it isn't the right approach.

2023-07-24 10:50 UTC, closed without merging