Replace kAverageHeight with XR_REFERENCE_SPACE_TYPE_STAGE
Igalia/wolvic pull request #860
Opened 2023-07-25 16:25 UTC by HollowMan6

We should not have to use kAverageHeight and those nasty tricks.

This is of course not ready as we have to test it and fix issues when we encounter them.

Reference: https://registry.khronos.org/OpenXR/specs/1.0/man/html/XrReferenceSpaceType.html

2023-07-25 16:45 UTC, HollowMan6 commented
Known issues:
1. The controllers appear very high when tracking off.
2. The screen appears very close to the face when heads up.

2023-07-26 07:31 UTC, svillar requested changes
So there is a fundamental issue with the patch that I'd like you to know before going on. The stage reference space is not supported in every device. As you can see we have specific code in case it's supported.

2023-07-26 07:31 UTC, svillar commented on app/src/oculusvr/cpp/DeviceDelegateOculusVR.cpp
> -const vrb::Vector kAverageOculusHeight(0.0f, 1.65f, 0.0f);
You can leave this file untouched, we don't plan to maintain the deprecated OculusVR backend. We're just keeping it there for a while for reference, but will eventually remove it.

2023-07-26 08:20 UTC, HollowMan6 commented
> So there is a fundamental issue with the patch that I'd like you to know before going on. The stage reference space is not supported in every device. As you can see we have specific code in case it's supported.

Ah, Okay ... Maybe at least I will try to make this change work for Meta Quest 2 or in case it's supported.

2023-07-26 11:19 UTC, svillar commented
> > So there is a fundamental issue with the patch that I'd like you to know before going on. The stage reference space is not supported in every device. As you can see we have specific code in case it's supported.
> 
> Ah, Okay ... Maybe at least I will try to make this change work for Meta Quest 2 or in case it's supported.

Yeah in general we should avoid doing per-device fixes and focus only on capabilities, after all that's the whole point of OpenXR

2023-07-29 16:00 UTC, HollowMan6 commented
#734 can be a very good addition to this so that we can have some control over the window distance.

2023-07-29 16:19 UTC, HollowMan6 commented
It might be better to continue using XR_REFERENCE_SPACE_TYPE_LOCAL, XR_REFERENCE_SPACE_TYPE_STAGE looks a little bit odd (Windows are a little bit high), especially when heads up.

2023-09-05 17:58 UTC, HollowMan6 commented
Let's close this, don't think this is a useful PR.

2023-09-05 17:58 UTC, closed without merging