Bypass download uri cache when user tries to download again
Igalia/wolvic pull request #968
Opened 2023-09-13 11:12 UTC by HollowMan6

Resolve #353

Kind of nasty, but can't think of a better way.

2023-09-15 08:25 UTC, svillar requested changes
I think we need to think in a better way to solve this. No ideas ATM but will think about it (not high prio anyway)

2023-09-30 14:49 UTC, HollowMan6 commented
Close as solved by #1034

2023-09-30 16:03 UTC, HollowMan6 commented
Reopen as an upgrade to Gecko 120 doesn't resolve this (my mistake) ...

2023-11-07 20:19 UTC, HollowMan6 commented
Superseded by #1100

2023-11-07 20:19 UTC, closed without merging