Enable custom URIs on Meta
Igalia/wolvic pull request #991
Opened 2023-09-20 03:28 UTC by felipeerias

This PR enables support on Meta for custom URIs that start with `wolvic://com.igalia.wolvic`

This functionality was accidentally removed on Meta.

It can be tested from the command line with:

    adb shell am start -a android.intent.action.VIEW -d  "wolvic://com.igalia.wolvic/?url=wikipedia.org"

2023-09-20 08:04 UTC, javifernandez reviewed
We already have this intent in the main manifest file. As a matter of fact, the merged manifest for debug builds have this intent as well. 

I think the problem is that we are not setting correctly the merging priorities for release builds. I'd rather investigate this instead of adding a redundant intent in the flavor specific manifest.

2023-09-20 11:58 UTC, svillar requested changes

2023-09-20 11:58 UTC, svillar commented on app/src/oculusvrArmRelease/AndroidManifest.xml
> +            </intent-filter>
As @javifernandez said we have exactly this code in the main manifest.

2023-09-21 14:02 UTC, svillar commented
OK, so @felipeerias found that for meta store we're actually replacing the `<activity>` from the main manifest, that's why no intent filters from main are considered.

@felipeerias please do include the other two `intent-filter`s in this patch. We'll evaluate later whether the `replace` does still make sense

2023-09-25 09:37 UTC, closed without merging